// src/components/Features.js
import React from 'react';
import './Features.css';

const features = [
  {
    title: 'Team Planning',
    desc: 'Collaborate with teammates in real-time to add itineraries and assign tasks, making travel preparation more efficient.',
    icon: '👥',
  },
  {
    title: 'AI Itinerary Suggestions',
    desc: 'Enter your city and preferences to receive personalized travel plans generated by AI.',
    icon: '🤖',
  },
  {
    title: 'Visual Trip Dashboard',
    desc: 'Get a clear overview of your entire travel plan — organized by time, location, and participants.',
    icon: '📊',
  },
  {
    title: 'Travel Footprint Logging',
    desc: 'Upload photos and pin locations to automatically log every stop you have made.',
    icon: '🗺️',
  },
  {
    title: 'Task Assignment & Reminders',
    desc: 'Easily assign tasks with gentle reminders, helping everyone stay on track and enjoy planning the journey together.',
    icon: '⏰',
  },
  {
    title: 'Packing & Cost Splitting',
    desc: 'Create packing checklists and share trip expenses transparently — reducing conflicts and enhancing your travel experience.',
    icon: '💼',
  },
];

function Features() {
  return (
    <>
    <section className="features-section">
      <h2 className="features-heading">Core Functions</h2>
      <div className="features-grid">
        {features.map((f, i) => (
          <div className="feature-card" key={i}>
            <div className="feature-icon">{f.icon}</div>
            <h3>{f.title}</h3>
            <p className="subtitle">{f.subtitle}</p>
            <p className="desc">{f.desc}</p>
          </div>
        ))}
      </div>
    
        <footer className="footer">
        <p>Designed & Developed by Siyu Jin</p>
        </footer>
    </section>
    </>
  );
}

export default Features;
